### ISSUE TITLE
Description update?

### ISSUE THREAD

**Issue by vvpeter** [carsongmiller/RAWBurstModeExtractor#1]
The description of this utility says it results in RAW files being output, but I'm only seeing DNG files.  Should the description be changed to reflect that, or is there some other way to run this which results in the individual RAW/CR3 files being generated from the burst mode original file?

**Comment by carsongmiller** [comment]
Yeah, I guess I usually just consider DNG's to be like open source RAW files, but maybe they're technically not. You can also embed the RAW file within the DNG itself, but with raw burst mode shots, that would mean each resulting image would be at least as large as the original.

This would be done by changing the option for embed-raw to true. 

The description does say that it extracts DNG's, but if you can point me to something else that was confusing, please do.

**Comment by vvpeter** [comment]
yeah, that's what I just tested.  The embed option of true just puts the original burst-mode file contents in each DNG file.  All I'm after is just getting the individual RAW files extracted from a single Burst file, not needing the DNG files (I'm using the Canon DPP app to edit the burst files but it also does not support a single-step mass extraction of the burst file contents).  I thought this utility w/your front-end might help w/that.  It does generate individual DNG files but I'm at a loss after that to get them to the individual CR3 raw content/format.
________________________________

**Comment by carsongmiller** [comment]
Totally understandable. For what it's worth, I'd try just proceeding with the DNG files to do whatever editing you need to do. Unless your workflow specifically requires CR3's, I'd say it's very possible you won't notice a difference between the DNG's that DNGLab gives you and the CR3's DPP gives you. I'd say the general consensus from what I can tell is that people treat DNG's as equivalent to RAW's--until now I thought they actually were RAW (and I'm still not sure they aren't). Even programs like topaz treat DNG's as just a standard RAW file format, and if you perform an AI denoise in Lightroom, it gives you a new DNG, stacked on top of the original CR3, with all of your edits applied to it, and I can't notice any difference when then editing the CR3.

**Comment by vvpeter** [comment]
right now my workflow has been DPP which unfortunately doesn't support DNG files and they only allow extracting burst images 1 at a time.  I'll try some other programs that use DNG because I do so many burst-mode shots (mainly wildlife).  The pricing on Lightroom doesn't look too bad.  I need to try Darktable first - it looks pretty good, has DNG support and is open source.  I only need minor editing since I'm mainly doing cropping and then saving to jpeg.  If it works, my workflow will be using dnglab to generate all the DNGs, using darktable/lightroom to review them, edit/crop/export the ones I'll keep, delete the rest of the dng files and then change the keeper dng filenames to relate to the original burst mode filename and archive those files.
________________________________

**Comment by carsongmiller** [comment]
Nice, sounds like that could work pretty well

**Comment by vvpeter** [comment]
I also saw the Canon EDSDK Raw sdk - I'm not sure if it can be used to access raw burst files to write a utility to pull all the images out but it's worth a look.  I sent them an email asking about it as well.
________________________________

**Comment by carsongmiller** [comment]
Yeah could be cool. I even went through the process (before I realized canon had just an open SDK) to use dependency walker to see what DLL's DPP was using when extracting RAW's, and I was gonna try and figure out how to use them to perform the same task. Would've been a ton of work though. 

But DNGLab also does have a UI planned. If you really want to make one, that could be the most pragmatic way to get a UI for this sort of stuff--contribute to the project.

**Comment by vvpeter** [comment]
It strikes me as odd that dnglab doesn't have an option to output CR3 files since they can obviously already process the burst image file contents....
________________________________

**Comment by vvpeter** [comment]
I put a discussion/idea entry on the dnglab git to add a CR3 RAW option - see if it goes anywhere...
________________________________

**Comment by carsongmiller** [comment]
Nice, let me know if you hear anything

**Comment by vvpeter** [comment]
I posted to the Canon SDK forum as well in addition to the email I sent them about the SDK for RAW
________________________________

**Comment by vvpeter** [comment]
I just went thru their different SDK docs, including the one for RAW and there was no mention of burst/roll files in the apis so I'm guessing it'll be a bust on the SDK side.  I'll bust their chops about it if they do actually respond.
________________________________

**Comment by carsongmiller** [comment]
By the way, did you find the program easy to use?  Anything annoying?

**Comment by vvpeter** [comment]
One more thing I noticed is that for me the Image Preview is throwing an error: Error refreshing preview image.  The type initializer for 'NativeMagickSettings' threw an exception.

It then leaves the cursor in the spinning state although things can still be selected.

Let me know if you want me to create a new issue for it.
________________________________

**Comment by carsongmiller** [comment]
Did you compile the program yourself, or use the precompiled version?  If you compiled yourself, you'll need to restore the nuget packages (there are two required packages: Magick.NET.SystemDrawing and Magick.NET-Q16-AnyCPU)

**Comment by vvpeter** [comment]
I just went w/the precompiled
________________________________

**Comment by carsongmiller** [comment]
Did you run it in the same library as those DLL's?
